<?php if ($this->pageCount) : ?>
    <nav aria-label="Page navigation">
      <ul class="pagination">
        <li>
            <?php if (isset($this->previous)): ?>
              <a href="<?php echo $this->url($this->route, [ 'page' => $this->previous ]) ?>" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a>
          <?php else: ?>
            <span aria-hidden="true" class="disabled">&laquo;</span>
        <?php endif; ?>
    </li>
    <?php foreach ($this->pagesInRange as $page):?>
        <?php if ($page != $this->current): ?>
            <li><a href="<?php echo $this->url($this->route, [ 'page' => $page ]) ?>"><?php echo $page; ?></a></li>
        <?php else: ?>
            <li class="active"><a href="<?php echo $this->url($this->route, [ 'page' => $page ]) ?>"><?php echo $page; ?></a></li>
        <?php endif; ?>
    <?php endforeach; ?>
    <li>
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->url($this->route, [ 'page' => $this->next ]) ?>" aria-label="Next"><span aria-hidden="true">&raquo;</span></a>
        <?php else: ?>
            <span aria-hidden="true" class="disabled">&raquo;</span>
        <?php endif; ?>
    </li>
</ul>
</nav>
<?php endif; ?>
