<?php
$type = $this->type;
?>

<h1>Fiche du Type : <?php echo $this->escapeHtml($type->getName()); ?></h1>

<p><b>Nom : </b> <?php echo $this->escapeHtml($type->getName()); ?></p>
<p><b>Couleur : </b> <span class="label" style="background: <?php echo $this->escapeHtml($type->getColor()); ?>;"><?php echo $this->escapeHtml($type->getColor()); ?></span></p>

<p>
	<a class="btn btn-warning" href="<?php echo $this->url('type_edit', ['typeId' => $type->getId()]) ;?>">
		<i class="glyphicon glyphicon-pencil"></i> Modifier
	</a>
	<a class="btn btn-danger" href="<?php echo $this->url('type_delete', ['typeId' => $type->getId()]) ;?>">
		<i class="glyphicon glyphicon-remove"></i> Supprimer
	</a>
</p>