<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta hhtp-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" cotent="width=device-width, initial-scale=1">
  <?= $this->headTitle('Pokedex Zend')->setSeparator(' - ')->setAutoEscape(false) ?>
  <link href="" rel="icon" type="image/x-icon" />

  <?= $this->headMeta()
  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?= $this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => 'data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIAACIiAAIiIiACIiIgAiIiIiIiIiACIhIiIiIiIAAiESIiIiIAACIiIiIiIgAAAiIiIiIgAAAAAiIiIAAAAAAAAAAAAAD4HwAA5+cAAN/7AAC//QAAvn0AAH2+AABBggAAAYAAAAAAAAAAAAAAAAAAAIABAACAAQAAwAMAAOAHAAD4HwAA'])
  ->prependStylesheet($this->basePath('css/style_pokemon_index.css'))
  ?>
  <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">


  <!-- Scripts -->
  <?= $this->headScript()
  ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
  ?>
</head>

<body>

  <nav class="light-blue darken-4">
    <div class="nav-wrapper container">
      <a href="<?= $this->url('pokemon_home') ?>" class="brand-logo">Pokedex Zend</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <?php
        if(!$this->identity()){
          ?>
          <li><a href="<?= $this->url('user_login') ?>">Se connecter</a></li>
          <?php
        }
        else{
          ?>
          <li><a href="<?= $this->url('user_logout') ?>">Se déconnecter</a></li>
          <?php
        }
        ?>
      </ul>

    </div>
  </nav>

  <div class="row container">

    <?= $this->content ?>

  </div>

  <footer class="page-footer light-blue darken-4">
    <div class="footer-copyright">
      <div class="container center-align">
        Pokedex Zend
      </div>
    </div>
  </footer>

  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
</body>
</html>