<?= $this->doctype() ?>
<html>
<head>
    <meta charset="utf-8">
    <meta hhtp-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" cotent="width=device-width, initial-scale=1">
    <?= $this->headTitle('Pokedex Zend')->setSeparator(' - ')->setAutoEscape(false) ?>
    <link href="" rel="icon" type="image/x-icon" />

    <?= $this->headMeta()
    ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'icon', 'type' => 'image/x-icon', 'href' => 'data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAA////AAAA/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIAACIiAAIiIiACIiIgAiIiIiIiIiACIhIiIiIiIAAiESIiIiIAACIiIiIiIgAAAiIiIiIgAAAAAiIiIAAAAAAAAAAAAAD4HwAA5+cAAN/7AAC//QAAvn0AAH2+AABBggAAAYAAAAAAAAAAAAAAAAAAAIABAACAAQAAwAMAAOAHAAD4HwAA'])
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <!-- Scripts -->
    <?= $this->headScript()
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
    ?>
</head>
<body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">Pokedex Zend</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<?= $this->url('home') ?>">Home</a></li>
            <li><a href="<?= $this->url('pokemon_home') ?>">Pokémon</a></li>
            <li><a href="<?= $this->url('type_home') ?>">Type</a></li>
            <li><a href="<?= $this->url('location_home') ?>">Location</a></li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <?php
            if($this->identity()){
                ?>
                <li><a href="<?= $this->url('user_logout') ?>"><span class="glyphicon glyphicon-log-out"></span> Se déconnecter</a></li>
                <?php
            }
            else{
                ?>
                <li><a href="<?= $this->url('user_login') ?>"><span class="glyphicon glyphicon-log-in"></span> Se connecter</a></li>
                <?php
            }
            ?>
        </ul>
    </div>
</div>
</nav>
<div class="container">
    <?= $this->content ?>
</div>
</body>
</html>