<?php
$form = $this->form;
$form->prepare();
?>
<h1>Modification d'un Pokémon</h1>
<?php
echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('national_id')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('name')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('description')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('type1')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('type2')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('previous_pokemon')); ?>
		</p>
	</div>
</div>

<p>
	<?php echo $this->formSubmit($form->get('submit')); ?>

</p>
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->form()->closeTag(); ?>