<?php
$form = $this->form;
$form->prepare();
?>
<h1>Moodification d'un Pokémon</h1>

<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
    <?php echo $this->formRow($form->get('national_id')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('name')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('description')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('type1')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('type2')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('previous_pokemon')); ?>
</div>

<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>
