<h3>Pokemon</h3>
<a class="btn btn-primary" href="<?php echo $this->url("pokemon_add"); ?>">Ajouter un Pokémon !</a>

<?php if (!empty($this->pokemons)) : ?>
    <?php foreach ($this->pokemons as $pokemon) : ?>
        <hr />
        <div class="row">
            <div class="col-md-5">
    <img src="http://assets.pokemon.com/assets/cms2/img/pokedex/detail/<?php echo $this->escapeHtml($pokemon->getNationalId()); ?>.png" style="width: 40px;height: 40px;">  
    </div>
            <div class="col-md-5">
                <strong>
                    <a href="<?php echo $this->url(
                      'pokemon_show', [
                        'pokemonName' => $pokemon->getName()
                      ]); ?>">
                      <?php echo $this->escapeHtml($pokemon->getName()); ?>
                    </a>
                </strong>
            </div>
        </div>
    <?php endforeach; ?>
<?php else : ?>
    <div>Aucun Pokémon à afficher</div>
<?php endif; ?>
<hr />
<?php
    echo $this->paginationControl(
      $this->pokemons,
      'Sliding',
      'partial/pagination',
      ['route' => 'pokemon_home/paged']
    );
?>
