-- MySQL Script generated by MySQL Workbench
-- 07/15/17 01:30:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pokedex_zend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pokedex_zend
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pokedex_zend` DEFAULT CHARACTER SET utf8 ;
USE `pokedex_zend` ;

-- -----------------------------------------------------
-- Table `pokedex_zend`.`pokemon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex_zend`.`pokemon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `national_id` VARCHAR(3) NULL,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex_zend`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex_zend`.`type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pokedex_zend`.`pokemon_has_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pokedex_zend`.`pokemon_has_type` (
  `pokemon_id` INT NOT NULL,
  `type_id` INT NOT NULL,
  PRIMARY KEY (`pokemon_id`, `type_id`),
  INDEX `fk_pokemon_has_type_type1_idx` (`type_id` ASC),
  INDEX `fk_pokemon_has_type_pokemon_idx` (`pokemon_id` ASC),
  CONSTRAINT `fk_pokemon_has_type_pokemon`
    FOREIGN KEY (`pokemon_id`)
    REFERENCES `pokedex_zend`.`pokemon` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pokemon_has_type_type1`
    FOREIGN KEY (`type_id`)
    REFERENCES `pokedex_zend`.`type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
