<?php
$form = $this->form;
$form->prepare();
?>
<h1>Moodification d'un Location</h1>

<?php echo $this->form()->openTag($form); ?>

<div class="form-group">
  <?php echo $this->formRow($form->get('pokemon')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('long')); ?>
</div>
<div class="form-group">
  <?php echo $this->formRow($form->get('lat')); ?>
</div>
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>

<br>

<button type="button" id="findLocation" class="btn btn-success">Rafraichir ma position</button>

<script>
	var url = "https://www.googleapis.com/geolocation/v1/geolocate?key=";
	var key = "AIzaSyCbPa7paIr3MGlLVMMm6L6bFuvcDhECpP8";

	function findLocation(){
		$.ajax({
			type : 'POST',
			url: url + key, 
			success: function(result){
				$('input[name=lat]').val(result['location']['lat']);
				$('input[name=long]').val(result['location']['lng']);
			}});
	}

	$(document).ready(function() {
		findLocation();

		$("#findLocation").click(function() {
			findLocation();
		});
	});

</script>