<?php
$form = $this->form;
$form->prepare();
?>
<h1>Modification d'une Localisation</h1>
<?php
echo $this->form()->openTag($form);
?>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('pokemon')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('lat')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<?php echo $this->formRow($form->get('long')); ?>
		</p>
	</div>
</div>
<div class="row">
	<div class="form-group col-lg-5">
		<p>
			<button type="button" id="findLocation" class="btn btn-success">Rafraichir ma position</button>
		</p>
	</div>
</div>

<p>
	<?php echo $this->formSubmit($form->get('submit')); ?>

</p>
<?php echo $this->formRow($form->get('id')); ?>
<?php echo $this->form()->closeTag(); ?>

<script>
	var url = "https://www.googleapis.com/geolocation/v1/geolocate?key=";
	var key = "AIzaSyCbPa7paIr3MGlLVMMm6L6bFuvcDhECpP8";

	function findLocation(){
		$.ajax({
			type : 'POST',
			url: url + key, 
			success: function(result){
				$('input[name=lat]').val(result['location']['lat']);
				$('input[name=long]').val(result['location']['lng']);
			}});
	}

	$(document).ready(function() {
		findLocation();

		$("#findLocation").click(function() {
			findLocation();
		});
	});

</script>